use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ErrorCode {
    AlreadyInitialized = 1,
    NotAuthorized = 2,
    MarketNotFound = 3,
    MarketClosed = 4,
    MarketStillActive = 5,
    InvalidOutcome = 6,
    InvalidBetAmount = 7,
    InsufficientBalance = 8,
    OracleFailure = 9,
    CircuitBreakerOpen = 10,
    DisputeWindowClosed = 11,
    AlreadyVoted = 12,
    FeeTooHigh = 13,
    MarketNotActive = 14,
    DeadlinePassed = 15,
    CannotChangeOutcome = 16,
    MarketNotDisputed = 17,
    MarketNotPendingResolution = 18,
    AdminNotSet = 19,
    ContractPaused = 20,
    GuardianNotSet = 21,
    TooManyOutcomes = 22,
    TooManyWinners = 23,
    PayoutModeNotSupported = 24,
    InsufficientDeposit = 25,
    TimelockActive = 26,
    UpgradeNotInitiated = 27,
    InsufficientVotes = 28,
    AlreadyVotedOnUpgrade = 29,
    InvalidWasmHash = 30,
    UpgradeFailed = 31,
    ParentMarketNotResolved = 32,
    ParentMarketInvalidOutcome = 33,
    InsufficientVotingWeight = 34,
    MarketNotCancelled = 35,
    BetNotFound = 36,
    ResolutionNotReady = 37,
    StalePrice = 38,
    ConfidenceTooLow = 39,
    DisputeWindowStillOpen = 40,
    NoMajorityReached = 41,
    AssetClawedBack = 42,
    GovernanceTokenNotSet = 43,
    InvalidAmount = 44,
    NoWinnings = 45,
    MarketNotResolved = 46,
    AlreadyClaimed = 47,
    InvalidReferrer = 48,
    GracePeriodActive = 49,
    InvalidDeadline = 50,
    VotingPeriodNotElapsed = 51,
    VotingNotStarted = 52,
    VotingEnded = 53,
    InvalidTimestamp = 54,
    ResolutionDeadlinePassed = 55,
    MarketIdOverflow = 56,
    MarketIdCollision = 57,
}
